# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=30)),
                ('local', models.CharField(max_length=10)),
                ('tel', models.CharField(max_length=20)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('wifi', models.BooleanField()),
                ('plug', models.BooleanField()),
                ('table', models.IntegerField()),
                ('floor', models.CharField(max_length=5)),
                ('time_killing', models.FloatField()),
                ('reading_books', models.FloatField()),
                ('studying', models.FloatField()),
                ('web_surfing', models.FloatField()),
                ('beverage', models.FloatField()),
                ('dessert', models.FloatField()),
                ('quiet', models.FloatField()),
                ('kind', models.FloatField()),
                ('score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wifi', models.BooleanField()),
                ('plug', models.BooleanField()),
                ('table', models.IntegerField()),
                ('floor', models.CharField(max_length=5)),
                ('time_killing', models.FloatField()),
                ('reading_books', models.FloatField()),
                ('studying', models.FloatField()),
                ('web_surfing', models.FloatField()),
                ('beverage', models.FloatField()),
                ('dessert', models.FloatField()),
                ('quiet', models.FloatField()),
                ('kind', models.FloatField()),
                ('status', models.BooleanField()),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.Cafe')),
            ],
        ),
    ]
